# Generated by Django 4.2.16 on 2024-10-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_doctor_joining_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientbilling',
            name='admission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientbilling',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='patientbilling',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
