# Generated by Django 4.2.16 on 2024-10-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_department_remove_doctor_joining_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
