# Generated by Django 4.2.16 on 2024-10-29 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_remove_doctor_employee_doctor_joining_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='joining_date',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='photo',
        ),
        migrations.AddField(
            model_name='doctor',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='hospital.employee'),
        ),
    ]
