# Generated by Django 4.2.16 on 2024-11-04 13:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_report_notice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='description',
        ),
        migrations.RemoveField(
            model_name='report',
            name='generated_by',
        ),
        migrations.RemoveField(
            model_name='report',
            name='parameters',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='marriage_certificate',
            field=models.FileField(blank=True, null=True, upload_to='marriage_certificates/'),
        ),
        migrations.AddField(
            model_name='report',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='hospital.department'),
        ),
        migrations.AddField(
            model_name='report',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='hospital.doctor'),
        ),
        migrations.AddField(
            model_name='report',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='hospital.patient'),
        ),
        migrations.AddField(
            model_name='report',
            name='prescriptions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='treatment_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('annual', 'Annual Leave'), ('sick', 'Sick Leave'), ('maternity', 'Maternity Leave'), ('paternity', 'Paternity Leave'), ('marriage', 'Marriage Leave'), ('unpaid', 'Unpaid Leave'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('lab', 'Laboratory Report'), ('rad', 'Radiology Report'), ('path', 'Pathology Report'), ('op', 'Operation Report'), ('dis', 'Discharge Summary'), ('prog', 'Progress Report')], max_length=10),
        ),
        migrations.CreateModel(
            name='ReportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='report_attachments/')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='hospital.report')),
            ],
        ),
    ]
